// Mobile/src/constants/crops.js

export const CROP_TYPES = [
  "Teff",
  "Red Onion",
  "Tomato",
  "Garlic",
  "White Maize",
  "Wheat",
  "Barley",
  "Sorghum",
  "Millet",
  "Green Pepper",
  "Cabbage",
  "Potato",
  "Carrot",
  "Beetroot",
  "Coffee",
  "Sesame",
  "Lentil",
  "Chickpea",
  "Haricot Bean",
  "Papaya",
];

export const CROP_TYPES_LOCALIZED = {
  en: {
    Teff: "White Teff",
    "Red Onion": "Red Onion",
    Tomato: "Fresh Tomato",
    Garlic: "White Garlic",
    "White Maize": "White Maize",
    Wheat: "Bread Wheat",
    Barley: "Malt Barley",
    Sorghum: "White Sorghum",
    Millet: "Finger Millet",
    "Green Pepper": "Green Pepper (Kariya)",
    Cabbage: "Head Cabbage",
    Potato: "White Potato",
    Carrot: "Fresh Carrot",
    Beetroot: "Red Beetroot",
    Coffee: "Arabica Coffee",
    Sesame: "Humera Sesame",
    Lentil: "Red Lentil",
    Chickpea: "Kabuli Chickpea",
    "Haricot Bean": "White Pea Bean (Boleqe)",
    Papaya: "Sweet Papaya",
  },
  am: {
    Teff: "ማግና (ነጭ) ጤፍ",
    "Red Onion": "ቀይ ሽንኩርት",
    Tomato: "ቲማቲም",
    Garlic: "ነጭ ሽንኩርት",
    "White Maize": "ነጭ በቆሎ",
    Wheat: "ስንዴ",
    Barley: "ገብስ",
    Sorghum: "ማሽላ",
    Millet: "ዳጉሣ",
    "Green Pepper": "ቃሪያ",
    Cabbage: "ጎመን",
    Potato: "ድንች",
    Carrot: "ካሮት",
    Beetroot: "ቀይ ስር",
    Coffee: "ቡና",
    Sesame: "ሰሊጥ",
    Lentil: "ምስር",
    Chickpea: "ሽምብራ",
    "Haricot Bean": "ቦሌቄ",
    Papaya: "ፓፓያ",
  },
  om: {
    Teff: "Xaafii Adii (Magna)",
    "Red Onion": "Qasaricha Diimaa",
    Tomato: "Xaafii Diimaa (Timaatimi)",
    Garlic: "Qasaricha Adii",
    "White Maize": "Boqqoolloo Adii",
    Wheat: "Qamadii",
    Barley: "Garbuu",
    Sorghum: "Misingaa",
    Millet: "Dagusa",
    "Green Pepper": "Kariyaa",
    Cabbage: "Damma",
    Potato: "Dinnicha",
    Carrot: "Kaarotii",
    Beetroot: "Dinnicha Diimaa",
    Coffee: "Buna",
    Sesame: "Salxiqi",
    Lentil: "Misira",
    Chickpea: "Shimbiraa",
    "Haricot Bean": "Boleqe (Buna Dachee)",
    Papaya: "Papaayyaa",
  },
};

export const DEFAULT_DESCRIPTIONS_LOCALIZED = {
  en: {
    Teff: "Magna (White) Teff, freshly harvested. Thoroughly sifted, cleaned, and grown strictly without chemical residues.",
    "Red Onion": "Red Bombay onion, medium to large size. Well-cured and dry. Sourced directly from local cooperative farms.",
    Tomato: "Fresh Rift Valley tomatoes, fully ripe and firm. Harvested this morning from local irrigation farms.",
    Garlic: "Dry white garlic bulbs. Strong flavor and aroma. Properly cured for extended shelf life.",
    "White Maize": "White maize, premium quality. Properly dried and cleaned grain, ready for milling or direct sale.",
    Wheat: "High-yield bread wheat, this season's harvest. Dry, clean, and well-stored. Perfect for flour milling.",
    Barley: "Premium malt barley, uniform grain size and high germination rate for brewing and food processing.",
    Sorghum: "Clean white sorghum, dry grain harvested from Rift Valley lowlands.",
    Millet: "High-nutrient finger millet, thoroughly winnowed and ready for traditional foods and beverages.",
    "Green Pepper": "Fresh green peppers (Kariya). Plump, unblemished, and uniform in size. Harvested this week.",
    Cabbage: "Fresh, tightly packed green cabbage. Farm-fresh with crisp leaves, grown using local irrigation.",
    Potato: "White potato, uniform medium size. Freshly unearthed, cured, and stored in dry conditions.",
    Carrot: "Vibrant orange carrots, washed, sweet, and crisp. Harvested fresh from highland farms.",
    Beetroot: "Deep red beetroot, firm and medium-sized. Rich in color and nutrients.",
    Coffee: "Grade-1 Specialty Arabica coffee beans, sun-dried and hand-picked from Ethiopian highlands.",
    Sesame: "Export-grade Humera white sesame seeds. High oil content, thoroughly cleaned.",
    Lentil: "Split red lentils, thoroughly cleaned, dry, and free from debris.",
    Chickpea: "Large Kabuli chickpeas, uniform shape, dry and well-stored.",
    "Haricot Bean": "Export-grade white pea beans (Boleqe). Carefully sorted, clean, and dry.",
    Papaya: "Sweet Batu/Meki papaya. Smooth skin, medium-ripe, and carefully handled to avoid transit bruising.",
  },
  am: {
    Teff: "ማግና (ነጭ) ጤፍ፣ አዲስ የተሰበሰበ። ሙሉ ለሙሉ የተለቀመ፣ የተጸዳ፣ ምንም ኬሚካል ሳይጠቀሙ የተመረተ።",
    "Red Onion": "ቀይ ቦምቤ ሽንኩርት፣ መካከለኛ እስከ ትልቅ መጠን። ጠንካራ እና ደረቅ። ቁስለት ሳይኖር ከሕብረት ሥራ ማህበራት ቀጥታ የተሰጠ።",
    Tomato: "ትኩስ ሸለቆ ቲማቲም፣ ሙሉ ለሙሉ የደረሰ እና ጠንካራ። ዛሬ ጠዋት ከአካባቢው የመስኖ ማሳዎች የተሰበሰበ።",
    Garlic: "ደረቅ ነጭ ሽንኩርት። ጠንካራ ጣዕምና መዓዛ ያለው። ለረጅም ጊዜ እንዲቆይ በጥሩ ሁኔታ ተጠብቋል።",
    "White Maize": "ነጭ በቆሎ፣ ከፍተኛ ጥራት። በትክክል የደረቀ እና የተጸዳ ዘር፣ ለወፍጮ ወይም ለቀጥታ ሽያጭ ዝግጁ።",
    Wheat: "ከፍተኛ ምርት ስንዴ፣ የዚህ ወቅት ሰብል። ደረቅ፣ ንጹህ እና በጥሩ ሁኔታ የተቀመጠ። ለዱቄት ፋብሪካዎች ተስማሚ።",
    Barley: "ጥራት ያለው የገብስ ምርት፣ ለምግብ እና ለጠጅ/ቢራ ፋብሪካዎች ዝግጁ የሆነ።",
    Sorghum: "ንጹህ ነጭ ማሽላ፣ በጥሩ ሁኔታ የተሰበሰበ እና የደረቀ።",
    Millet: "ጥራት ያለው ዳጉሣ፣ ለባህላዊ ምግቦችና ጠጅ ዝግጅት የተጸዳ።",
    "Green Pepper": "ትኩስ ቃሪያ። ደንዳና፣ ቁስለት የሌለው እና ወጥ መጠን ያለው። በዚህ ሳምንት የተሰበሰበ።",
    Cabbage: "ትኩስ፣ ጠንካራ ጎመን። ከቅርብ ቦታ ቀጥታ ከማሳ፣ ሸካካ ቅጠሎች ያሉት።",
    Potato: "ነጭ ድንች፣ ወጥ መካከለኛ መጠን። አዲስ የተቆፈረ፣ ደረቅ ቦታ ላይ ተቀምጧል።",
    Carrot: "ትኩስ ካሮት፣ የተጣጠበ እና ጣፋጭ። ከደብር ማሳዎች የተሰበሰበ።",
    Beetroot: "ቀይ ስር፣ ጠንካራ እና መካከለኛ መጠን ያለው።",
    Coffee: "ደረጃ-1 የኢትዮጵያ አራቢካ ቡና፣ በፀሐይ የደረቀ እና በጥንቃቄ የተለቀመ።",
    Sesame: "ለወጪ ንግድ ደረጃ ሁመራ ነጭ ሰሊጥ፣ ከፍተኛ የዘይት መጠን ያለው።",
    Lentil: "የተሰነጠቀ ቀይ ምስር፣ ንጹህ እና ደረቅ።",
    Chickpea: "ትልቅ የካቡሊ ሽምብራ፣ በጥንቃቄ የተለቀመ እና የተቀመጠ።",
    "Haricot Bean": "ለወጪ ንግድ ደረጃ ቦሌቄ። በጥንቃቄ የተለቀመ፣ ንጹህ እና ደረቅ።",
    Papaya: "ጣፋጭ ባቱ/ሜኪ ፓፓያ። ለስላሳ ቆዳ፣ በጥንቃቄ የተያዘ።",
  },
  om: {
    Teff: "Xaafii Magna (Adii), haaraa sassaabame. Guutummaatti gara'amee, qulqullaa'ee fi maaddii tokko malee qotame.",
    "Red Onion": "Qasaricha Bombee Diimaa, dheerinni giddugaleessaa hanga guddaatti. Gogee fi jabaatadha.",
    Tomato: "Xaafii Diimaa Caaccuu Laftii Qorichaa, guutummaatti gabbatee fi cimaadha. Har'a ganama sassaabame.",
    Garlic: "Qasaricha Adii gogaa. Urgaa fi mi'aa cimaa qaba. Yeroo dheeraa akka turuuf sirriitti to'atame.",
    "White Maize": "Boqqoolloo adii, qulqullina ol aanaa. Akka gaaritti gogee fi qulqullaa'e.",
    Wheat: "Qamadii galii guddaa, xaa'oo kana. Gogaa, qulqulluu fi tolfamee kuufame.",
    Barley: "Garbuu gaarii qulqulluu, nyaata fi dhugaatiif qophii.",
    "Green Pepper": "Kariyaa haaraa. Gabbatee, dhukkubbii malee fi dheerinni qixa.",
    Cabbage: "Damma haaraa, jabaatee walitti qabame. Qonnaarraa kallattiidhaan.",
    Potato: "Dinnicha adii, dheerinni giddugaleessaa qixa. Haaraa baafame, gogee kuufame.",
    Coffee: "Buna Itoophiyaa sadarkaa 1ffaa, aduudhaan goge fi of eeggannoon sassaabame.",
    Sesame: "Salxiqi adii Humeeraa baasii alaatiif, cooma ol aanaa qabu.",
    "Haricot Bean": "Boleqe (Buna dachee) baasii gara alaatti erguuf. Har'oo to'annaan qoodame, qulqulluu.",
    Papaya: "Papaayyaa mi'awa Baatuu/Meekii. Gogaa laafaa, of eeggannoon qabame.",
  },
};

export const REFERENCE_PRICES = {
  Teff: { kg: 95, quintal: 9500 },
  "Red Onion": { kg: 45, quintal: 4500 },
  Tomato: { kg: 38, quintal: 3800 },
  Garlic: { kg: 120, quintal: 12000 },
  "White Maize": { kg: 22, quintal: 2200 },
  Wheat: { kg: 41, quintal: 4100 },
  Barley: { kg: 38, quintal: 3800 },
  Sorghum: { kg: 25, quintal: 2500 },
  Millet: { kg: 28, quintal: 2800 },
  "Green Pepper": { kg: 40, quintal: 4000 },
  Cabbage: { kg: 18, quintal: 1800 },
  Potato: { kg: 24, quintal: 2400 },
  Carrot: { kg: 30, quintal: 3000 },
  Beetroot: { kg: 28, quintal: 2800 },
  Coffee: { kg: 220, quintal: 22000 },
  Sesame: { kg: 140, quintal: 14000 },
  Lentil: { kg: 85, quintal: 8500 },
  Chickpea: { kg: 70, quintal: 7000 },
  "Haricot Bean": { kg: 65, quintal: 6500 },
  Papaya: { kg: 25, quintal: 2500 },
};

/**
 * Get localized display name for a crop key
 */
export const getLocalizedCropName = (cropKey, lang = "en", t = null) => {
  if (!cropKey) return "";
  if (t) {
    return t(`crops.${cropKey}`, {
      defaultValue: CROP_TYPES_LOCALIZED[lang]?.[cropKey] || CROP_TYPES_LOCALIZED.en?.[cropKey] || cropKey,
    });
  }
  return (
    CROP_TYPES_LOCALIZED[lang]?.[cropKey] ||
    CROP_TYPES_LOCALIZED.en?.[cropKey] ||
    cropKey
  );
};