// Ethiopia regions, zones, weredas, and towns/cities complete configuration
export const LOCATIONS = {
  Oromia: {
    zones: [
      "Arsi",
      "West Arsi",
      "Bale",
      "East Bale",
      "Borena",
      "Guji",
      "West Guji",
      "East Hararghe",
      "West Hararghe",
      "East Shewa",
      "West Shewa",
      "North Shewa",
      "Southwest Shewa",
      "East Welega",
      "West Welega",
      "Horo Guduru Welega",
      "Kellem Welega",
      "Jimma",
      "Illubabor",
      "Buno Bedele",
      "Oromia Special Zone Surrounding Finfinne",
    ],
    wereda: {
      Arsi: [
        "Aminya",
        "Aseko",
        "Asella Town",
        "Bale Gasa",
        "Bekoji Town",
        "Chole",
        "Digeluna Tijo",
        "Diksis",
        "Dodotana Sire",
        "Enkelo Wabe",
        "Gololcha",
        "Guna",
        "Hitosa",
        "Jeju",
        "Limuna Bilbilo",
        "Lude Hitosa",
        "Merti",
        "Munesa",
        "Robe",
        "Seru",
        "Sherka",
        "Sire",
        "Sude",
        "Tena",
        "Tiyo",
        "Abomsa Town",
        "Huruta Town",
        "Sagure Town",
        "Kersa Town",
        "Dera Town",
      ],
      "West Arsi": [
        "Adaba",
        "Arsi Negele",
        "Arsi Negele Town",
        "Dodola",
        "Dodola Town",
        "Gadab Asasa",
        "Kofele",
        "Kofele Town",
        "Kokosa",
        "Kore",
        "Nensebo",
        "Shala",
        "Shashemene",
        "Shashemene Town",
        "Siraro",
      ],
      Bale: [
        "Agarfa",
        "Agarfa Town",
        "Berbere",
        "Dinsho",
        "Gasera",
        "Goba",
        "Goba Town",
        "Gololcha",
        "Goro",
        "Guradamole",
        "Meda Welabu",
        "Robe Town",
        "Sinana",
        "Ali Town",
      ],
      "East Bale": [
        "Dawe Kachen",
        "Dawe Serer",
        "Ginir",
        "Ginir Town",
        "Gololcha",
        "Gura Damole",
        "Legehida",
        "Rayitu",
        "Sawena",
      ],
      Borena: [
        "Abaya",
        "Areo",
        "Dhas",
        "Dillo",
        "Dire",
        "Elwaye",
        "Gelana",
        "Gomole",
        "Miyo",
        "Moyale",
        "Moyale Town",
        "Teltele",
        "Yabelo",
        "Yabelo Town",
        "Mega Town",
      ],
      Guji: [
        "Adola",
        "Adola Town",
        "Ana Sora",
        "Bore",
        "Dama",
        "Girja",
        "Halata",
        "Liben",
        "Negele Borana Town",
        "Odo Shakiso",
        "Shakiso Town",
        "Uraga",
        "Wadera",
      ],
      "West Guji": [
        "Abaya",
        "Awasho",
        "Bule Hora",
        "Bule Hora Town",
        "Dugda Dawa",
        "Galana",
        "Hambela Wamena",
        "Kercha",
        "Melka Soda",
        "Suro Berguda",
        "Tore Town",
      ],
      "East Hararghe": [
        "Babille",
        "Babille Town",
        "Bedeno",
        "Chinaksen",
        "Deder",
        "Fedis",
        "Girawa",
        "Gola Odana Meyumuluke",
        "Gursum",
        "Haramaya",
        "Haramaya Town",
        "Jarso",
        "Kersa",
        "Kombolcha",
        "Kurfa Chele",
        "Meta",
        "Meyumuluke",
        "Midega Tola",
        "Aweday Town",
      ],
      "West Hararghe": [
        "Anchar",
        "Boke",
        "Burka Dimtu",
        "Chiro",
        "Chiro Town",
        "Darolebu",
        "Doba",
        "Gemechis",
        "Guba Koricha",
        "Habro",
        "Kumbi",
        "Mesela",
        "Mieso",
        "Oda Bultum",
        "Tulo",
        "Bedessa Town",
        "Gelemso Town",
        "Hirna Town",
      ],
      "East Shewa": [
        "Ada'a",
        "Adama",
        "Adama Town",
        "Adami Tullu and Jido Kombolcha",
        "Batu (Zway) Town",
        "Bora",
        "Boset",
        "Dodota",
        "Dugda",
        "Fentale",
        "Gimbichu",
        "Liben",
        "Lome",
        "Metehara Town",
        "Mojo Town",
        "Bishoftu Town",
        "Meki Town",
        "Awash Melkasa Town",
        "Wonji Town",
      ],
      "West Shewa": [
        "Abuna Ginde Beret",
        "Ambo",
        "Ambo Town",
        "Bako Tibe",
        "Bako Town",
        "Cobi",
        "Dano",
        "Dendi",
        "Dire Enchini",
        "Inchini Town",
        "Ejere",
        "Elfu",
        "Ginde Beret",
        "Guder Town",
        "Ilfata",
        "Jeldu",
        "Jibat",
        "Meta Robi",
        "Midakegn",
        "Nono",
        "Toke Kutaye",
      ],
      "North Shewa": [
        "Abichuna Gne'a",
        "Aleltu",
        "Degem",
        "Dera",
        "Fitche Town",
        "Gerar Jarso",
        "Hidabu Abote",
        "Jida",
        "Kuyu",
        "Wara Jarso",
        "Wuchale",
        "Yaya Gulele",
        "Gerba Guracha Town",
        "Muketuri Town",
      ],
      "Southwest Shewa": [
        "Amaya",
        "Becho",
        "Dawo",
        "Elu",
        "Goro",
        "Ilu",
        "Kersana Malima",
        "Seden Sodo",
        "Tole",
        "Waliso",
        "Waliso Town",
        "Wonchi",
        "Tullu Bolo Town",
      ],
      "East Welega": [
        "Diga",
        "Gida Kiremu",
        "Gobu Seyo",
        "Gudeya Bila",
        "Guto Gida",
        "Haro Limmu",
        "Ibantu",
        "Jimma Arjo",
        "Leka Dulecha",
        "Limmu",
        "Nekemte Town",
        "Nunu Kumba",
        "Sasiga",
        "Sibu Sire",
        "Wama Hagalo",
        "Gida Ayana Town",
        "Sire Town",
      ],
      "West Welega": [
        "Ayra",
        "Babo Gambel",
        "Boji Chekors",
        "Boji Dirmaji",
        "Dale Sedi",
        "Dale Wabera",
        "Genji",
        "Gimbi",
        "Gimbi Town",
        "Guliso",
        "Haru",
        "Homa",
        "Kiltu Kara",
        "Kondala",
        "Lalo Asabi",
        "Lata Sibu",
        "Mana Sibu",
        "Nejo",
        "Nejo Town",
        "Nole Kaba",
        "Sayo Nole",
        "Yubdo",
        "Mendi Town",
      ],
      "Horo Guduru Welega": [
        "Abay Chomen",
        "Abe Dongoro",
        "Amuru",
        "Guduru",
        "Hababo Tudela",
        "Horo",
        "Horo Bulluk",
        "Jardega Jarte",
        "Jimma Geneti",
        "Jimma Rare",
        "Shambu Town",
        "Fincha Town",
      ],
      "Kellem Welega": [
        "Anfillo",
        "Dale Sedi",
        "Dale Wabera",
        "Dembidolo Town",
        "Gawo Kebe",
        "Gidami",
        "Hawa Gelan",
        "Jimma Horo",
        "Lalo Kile",
        "Sayo",
        "Yemalogi Wele",
        "Mugi Town",
      ],
      Jimma: [
        "Agaro Town",
        "Chora Boter",
        "Dedo",
        "Gera",
        "Gomma",
        "Gumay",
        "Jimma Town",
        "Kersa",
        "Limmu Kosa",
        "Limmu Sakka",
        "Mana",
        "Mencho",
        "Nada",
        "Nonno Benja",
        "Omo Nada",
        "Omo Tarik",
        "Seka Chekorsa",
        "Setema",
        "Shebe Senbo",
        "Sigmo",
        "Sokoru",
        "Sokoru Town",
        "Tiro Afeta",
        "Limmu Genet Town",
      ],
      Illubabor: [
        "Ale",
        "Alge Sachi",
        "Bilo Nopha",
        "Bure",
        "Chewaka",
        "Darimu",
        "Didu",
        "Doreni",
        "Gechi",
        "Hallelu",
        "Hurumu",
        "Meko",
        "Metu",
        "Metu Town",
        "Nono",
        "Supena Sodo",
        "Yayu",
        "Gore Town",
      ],
      "Buno Bedele": [
        "Bedele",
        "Bedele Town",
        "Borecha",
        "Chewaka",
        "Chora",
        "Chora Town",
        "Dabo Hana",
        "Dedesa",
        "Gechi",
        "Mako",
      ],
      "Oromia Special Zone Surrounding Finfinne": [
        "Akaki",
        "Berek",
        "Burayu Town",
        "Holeta Town",
        "Legetafo Legedadi Town",
        "Mulo",
        "Sebeta Hawas",
        "Sebeta Town",
        "Sendafa Town",
        "Sululta",
        "Sululta Town",
        "Walmara",
        "Gelan Town",
        "Dukem Town",
      ],
    },
  },
  Sidama: {
    zones: ["Hawassa City", "Sidama Zone"],
    wereda: {
      "Hawassa City": [
        "Hawassa City Administration",
        "Hayek Dare",
        "Tula",
        "Mehal Ketema",
      ],
      "Sidama Zone": [
        "Dale",
        "Aleta Wondo",
        "Aleta Wondo Town",
        "Yirgalem Town",
        "Dilla Zuria",
        "Aroresa",
        "Wensho",
        "Bensa",
        "Leku Town",
        "Bensa Daye Town",
      ],
    },
  },
  "Central Ethiopia": {
    zones: ["Gurage", "Silte", "Hadiya", "Kembata Tembaro", "Halaba", "Yem"],
    wereda: {
      Gurage: [
        "Wolkite Town",
        "Butajira Town",
        "Abeshge",
        "Sodo",
        "Cheha",
        "Ezha",
        "Enemorina Eaner",
        "Gumer",
        "Agena Town",
      ],
      Silte: [
        "Worabe Town",
        "Silte Wereda",
        "Lanfro",
        "Sankurra",
        "Kibet Town",
        "Tora Town",
      ],
      Hadiya: [
        "Hossana Town",
        "Limo",
        "Misha",
        "Soro",
        "Ana Lemo",
        "Gibe",
        "Shone Town",
      ],
      "Kembata Tembaro": [
        "Durame Town",
        "Angacha",
        "Damboya",
        "Kedida Gamela",
        "Hadero Tunto Town",
        "Shinshicho Town",
      ],
      Halaba: ["Halaba Kulito Town", "Wera", "Guba"],
      Yem: ["Fofa Town", "Yem Special", "Saja Town"],
    },
  },
  "South Ethiopia": {
    zones: [
      "Wolaita",
      "Gamo",
      "Gofa",
      "South Omo",
      "Konso",
      "Derashe",
      "Amaro",
      "Burji",
    ],
    wereda: {
      Wolaita: [
        "Wolaita Sodo Town",
        "Areka Town",
        "Humbo",
        "Boditi Town",
        "Damot Gale",
        "Kindo Koysha",
        "Sodo Zuria",
        "Tebela Town",
      ],
      Gamo: [
        "Arba Minch City",
        "Chencha",
        "Chencha Town",
        "Mirab Abaya",
        "Kucha",
        "Dita",
        "Gerese Town",
        "Selam Ber Town",
      ],
      Gofa: [
        "Sawla Town",
        "Uba Debretsehay",
        "Zala",
        "Geze Gofa",
        "Melokoza",
        "Bulki Town",
      ],
      "South Omo": [
        "Jinka Town",
        "Hamer",
        "Banna Semay",
        "Debub Ario",
        "Dasenech",
        "Nyangatom",
        "Key Afer Town",
        "Turmi Town",
      ],
      Konso: ["Karati Town", "Konso Zuria", "Segen Town"],
      Derashe: ["Gidole Town", "Derashe Zuria"],
      Amaro: ["Kelle Town", "Amaro Zuria"],
      Burji: ["Soyama Town", "Burji Zuria"],
    },
  },
  "Southwest Ethiopia": {
    zones: ["Keffa", "Sheka", "Bench Sheko", "Dawro", "Konta", "West Omo"],
    wereda: {
      Keffa: [
        "Bonga Town",
        "Gimbo",
        "Chenna",
        "Decha",
        "Wacha Town",
        "Goba Town",
      ],
      Sheka: ["Masha Town", "Mappi", "Anderacha", "Yeki", "Tepi Town"],
      "Bench Sheko": [
        "Mizan Aman Town",
        "Semen Bench",
        "Debub Bench",
        "Sheko",
        "Siz Town",
      ],
      Dawro: ["Tarcha Town", "Isara", "Tocha", "Loma", "Mareka", "Waka Town"],
      Konta: ["Ameya Town", "Konta Special"],
      "West Omo": ["Maji Town", "Surma", "Bero", "Meinit Shasha", "Tum Town"],
    },
  },
  "Addis Ababa": {
    zones: [
      "Arada",
      "Gulele",
      "Yeka",
      "Kolfe Keranio",
      "Nifas Silk Lafto",
      "Lideta",
      "Akaki Kality",
      "Bole",
      "Kirkos",
      "Addis Ketema",
      "Lemi Kura",
    ],
    wereda: {
      Arada: [
        "Wereda 01",
        "Wereda 02",
        "Wereda 03",
        "Wereda 04",
        "Wereda 05",
        "Wereda 06",
      ],
      Gulele: [
        "Wereda 01",
        "Wereda 02",
        "Wereda 03",
        "Wereda 04",
        "Wereda 05",
        "Wereda 06",
      ],
      Yeka: [
        "Wereda 01",
        "Wereda 02",
        "Wereda 03",
        "Wereda 04",
        "Wereda 05",
        "Wereda 06",
      ],
      "Kolfe Keranio": [
        "Wereda 01",
        "Wereda 02",
        "Wereda 03",
        "Wereda 04",
        "Wereda 05",
        "Wereda 06",
      ],
      "Nifas Silk Lafto": [
        "Wereda 01",
        "Wereda 02",
        "Wereda 03",
        "Wereda 04",
        "Wereda 05",
        "Wereda 06",
      ],
      Lideta: [
        "Wereda 01",
        "Wereda 02",
        "Wereda 03",
        "Wereda 04",
        "Wereda 05",
        "Wereda 06",
      ],
      "Akaki Kality": [
        "Wereda 01",
        "Wereda 02",
        "Wereda 03",
        "Wereda 04",
        "Wereda 05",
        "Wereda 06",
      ],
      Bole: [
        "Wereda 01",
        "Wereda 02",
        "Wereda 03",
        "Wereda 04",
        "Wereda 05",
        "Wereda 06",
      ],
      Kirkos: [
        "Wereda 01",
        "Wereda 02",
        "Wereda 03",
        "Wereda 04",
        "Wereda 05",
        "Wereda 06",
      ],
      "Addis Ketema": [
        "Wereda 01",
        "Wereda 02",
        "Wereda 03",
        "Wereda 04",
        "Wereda 05",
        "Wereda 06",
      ],
      "Lemi Kura": [
        "Wereda 01",
        "Wereda 02",
        "Wereda 03",
        "Wereda 04",
        "Wereda 05",
      ],
    },
  },
  Afar: {
    zones: [
      "Awusi Rasu (Zone 1)",
      "Kilbet Rasu (Zone 2)",
      "Gabi Rasu (Zone 3)",
      "Fantena Rasu (Zone 4)",
      "Hari Rasu (Zone 5)",
    ],
    wereda: {
      "Awusi Rasu (Zone 1)": [
        "Asayita",
        "Asayita Town",
        "Dubti",
        "Dubti Town",
        "Afambo",
        "Elidar",
        "Mille",
        "Mille Town",
        "Logia Town",
        "Semera City",
      ],
      "Kilbet Rasu (Zone 2)": [
        "Abala",
        "Abala Town",
        "Dallol",
        "Berhale",
        "Berhale Town",
        "Erebti",
      ],
      "Gabi Rasu (Zone 3)": [
        "Awash Fentale",
        "Awash Town",
        "Amibara",
        "Gewane",
        "Gewane Town",
        "Bure Mudaytu",
        "Melka Werer Town",
      ],
      "Fantena Rasu (Zone 4)": [
        "Ewa",
        "Chifra",
        "Chifra Town",
        "Yalo",
        "Gulina",
      ],
      "Hari Rasu (Zone 5)": ["Telalak", "Dewewe", "Dawe", "Dalifage Town"],
    },
  },
  Amhara: {
    zones: [
      "North Wollo",
      "South Wollo",
      "North Shewa (Amhara)",
      "East Gojjam",
      "West Gojjam",
      "North Gondar",
      "South Gondar",
      "Central Gondar",
      "West Gondar",
      "Awi",
      "Wag Hemra",
      "Oromia Special Zone",
    ],
    wereda: {
      "North Wollo": [
        "Woldiya City",
        "Lalibela Town",
        "Habru",
        "Kobo",
        "Kobo Town",
        "Gidan",
        "Meket",
        "Raya Kobo",
        "Hara Town",
        "Mersa Town",
      ],
      "South Wollo": [
        "Dessie City",
        "Kombolcha City",
        "Tehuledere",
        "Kalu",
        "Ambasel",
        "Were Ilu",
        "Were Ilu Town",
        "Haiq Town",
        "Bistima Town",
      ],
      "North Shewa (Amhara)": [
        "Debre Berhan City",
        "Ankober",
        "Shewa Robit Town",
        "Ataye Town",
        "Menz",
        "Ensarot",
        "Efratana Gidim",
        "Alem Ketema Town",
      ],
      "East Gojjam": [
        "Debre Markos City",
        "Enarj Enawga",
        "Machakel",
        "Goza Amnen",
        "Bichena",
        "Bichena Town",
        "Dejen",
        "Dejen Town",
        "Mota Town",
      ],
      "West Gojjam": [
        "Finote Selam Town",
        "Bure",
        "Bure Town",
        "Bahar Dar Zuria",
        "Merawi Town",
        "Quarit",
        "Dembacha Town",
        "Jiga Town",
      ],
      "North Gondar": [
        "Debark",
        "Debark Town",
        "Addarkay",
        "Jan Amora",
        "Dabat Town",
      ],
      "South Gondar": [
        "Debre Tabor Town",
        "Addis Zemen Town",
        "Farta",
        "Lay Armachiho",
        "Ebinat",
        "Woreta Town",
      ],
      "Central Gondar": [
        "Gondar City",
        "Gondar Zuria",
        "Maksegnit Town",
        "Chilga",
        "Aykel Town",
      ],
      "West Gondar": [
        "Metema",
        "Metema Yohannes Town",
        "Quara",
        "Genda Wuha Town",
      ],
      Awi: [
        "Injibara Town",
        "Chagni Town",
        "Dangila",
        "Dangila Town",
        "Gimjabet Town",
        "Enjebara",
      ],
      "Wag Hemra": [
        "Sekota",
        "Sekota Town",
        "Dehana",
        "Zaquala",
        "Tsiquala Town",
      ],
      "Oromia Special Zone": [
        "Kemise City",
        "Bati Zuria",
        "Bati Town",
        "Jille Timuga",
        "Sanbete Town",
      ],
    },
  },
  "Dire Dawa": {
    zones: ["Dire Dawa City", "Dire Dawa Rural"],
    wereda: {
      "Dire Dawa City": [
        "01 Sub-City",
        "02 Sub-City",
        "03 Sub-City",
        "04 Sub-City",
        "05 Sub-City",
        "06 Sub-City",
        "Dire Dawa City Administration",
      ],
      "Dire Dawa Rural": ["Gurgura", "Wahil", "Bisa Dimo", "Melka Jebdu Town"],
    },
  },
  Gambela: {
    zones: ["Anywaa", "Nuer", "Majang", "Itang Special"],
    wereda: {
      Anywaa: [
        "Gambela City",
        "Gambela Zuria",
        "Abobo",
        "Abobo Town",
        "Gog",
        "Jor",
        "Pugnido Town",
      ],
      Nuer: ["Akobo", "Jikawo", "Lare", "Wantuwa", "Kuye Town"],
      Majang: ["Mengesh", "Godere", "Meti Town"],
      "Itang Special": ["Itang", "Itang Town"],
    },
  },
  Harari: {
    zones: ["Harar City", "Harari Rural"],
    wereda: {
      "Harar City": [
        "Harar City Administration",
        "Aboker",
        "Arada",
        "Jin'Ella",
        "Suqulat",
        "Amir Nur",
        "Shenkor",
      ],
      "Harari Rural": ["Sofi", "Erer", "Dire Teyara", "Hakim"],
    },
  },
  Somali: {
    zones: [
      "Fafan (Jijiga)",
      "Siti",
      "Gerdhari",
      "Liben",
      "Afder",
      "Shabelle",
      "Korahe",
      "Doolo",
      "Erer",
    ],
    wereda: {
      "Fafan (Jijiga)": [
        "Jijiga City",
        "Jijiga Zuria",
        "Babille (Somali)",
        "Gursum (Somali)",
        "Awbare",
        "Kebri Beyah Town",
        "Tuli Guled",
      ],
      Siti: [
        "Shinile",
        "Shinile Town",
        "Aisha",
        "Dembel",
        "Erer Wereda",
        "Mieso (Somali)",
        "Biki Town",
      ],
      Gerdhari: [
        "Degehabur",
        "Degehabur Town",
        "Aware",
        "Dhagaxbour",
        "Gunagado",
        "Birkod Town",
      ],
      Liben: [
        "Filtu",
        "Filtu Town",
        "Dolo Odo",
        "Dolo Odo Town",
        "Moyale (Somali)",
        "Hudet Town",
      ],
      Afder: [
        "Hargele",
        "Hargele Town",
        "Gode Zuria",
        "Elkere",
        "Bare",
        "Chereti Town",
      ],
      Shabelle: [
        "Gode City",
        "Kelafo",
        "Kelafo Town",
        "Mustahil",
        "Ferfer Town",
      ],
      Korahe: [
        "Kebri Dahar City",
        "Shilabo",
        "Kebridehar Zuria",
        "Shekosh Town",
      ],
      Doolo: ["Warder", "Warder Town", "Boh", "Galadi", "Danot Town"],
      Erer: ["Fiq", "Fiq Town", "Hamaro", "Lagahida Town"],
    },
  },
  Tigray: {
    zones: [
      "Mekelle City",
      "Central",
      "Eastern",
      "Southern",
      "South Eastern",
      "Northwestern",
      "Western",
    ],
    wereda: {
      "Mekelle City": [
        "Kedamay Weyane",
        "Hadnet",
        "Ayder",
        "Semien",
        "Hawelti",
        "Quiha Sub-City",
        "Mekelle City Administration",
      ],
      Central: [
        "Adwa",
        "Adwa Town",
        "Axum City",
        "Ahferom",
        "Mereb Lehe",
        "Enticho Town",
        "Rama Town",
      ],
      Eastern: [
        "Adigrat City",
        "Wukro Town",
        "Ganta Afeshum",
        "Gulomahda",
        "Bizet Town",
        "Edaga Hamus Town",
      ],
      Southern: [
        "Maichew Town",
        "Alamata",
        "Alamata Town",
        "Ofla",
        "Endamehoni",
        "Korem Town",
        "Chercher Town",
      ],
      "South Eastern": [
        "Samre",
        "Dogu'a Tembien",
        "Hintalo Wajirat",
        "Hagere Selam Town",
        "Gijet Town",
      ],
      Northwestern: [
        "Shire Indaselassie City",
        "Sheraro Town",
        "Medebay Zana",
        "Tselemt",
        "Seyemti Adiyabo",
        "Selekleka Town",
      ],
      Western: [
        "Humera Town",
        "Wolkayit",
        "Tsegede",
        "Dansha Town",
        "Kafta Humera",
        "Setit Humera Town",
      ],
    },
  },
};

export const REGIONS = Object.keys(LOCATIONS);

export const getZonesByRegion = (region) => {
  return LOCATIONS[region]?.zones || [];
};

export const getWeredaByZone = (region, zone) => {
  return LOCATIONS[region]?.wereda?.[zone] || [];
};

// ─── Localization ──────────────────────────────────────────────────────────
// Region and zone names are proper geographic names — translation here means
// how they're conventionally written/rendered in each language, not literal
// word-for-word translation.

export const REGIONS_LOCALIZED = {
  en: {
    Oromia: "Oromia",
    Sidama: "Sidama",
    "Central Ethiopia": "Central Ethiopia",
    "South Ethiopia": "South Ethiopia",
    "Southwest Ethiopia": "Southwest Ethiopia",
    "Addis Ababa": "Addis Ababa",
    Afar: "Afar",
    Amhara: "Amhara",
    "Dire Dawa": "Dire Dawa",
    Gambela: "Gambela",
    Harari: "Harari",
    Somali: "Somali",
    Tigray: "Tigray",
  },
  am: {
    Oromia: "ኦሮሚያ",
    Sidama: "ሲዳማ",
    "Central Ethiopia": "መካከለኛ ኢትዮጵያ",
    "South Ethiopia": "ደቡብ ኢትዮጵያ",
    "Southwest Ethiopia": "ደቡብ ምዕራብ ኢትዮጵያ",
    "Addis Ababa": "አዲስ አበባ",
    Afar: "አፋር",
    Amhara: "አማራ",
    "Dire Dawa": "ድሬ ዳዋ",
    Gambela: "ጋምቤላ",
    Harari: "ሐረሪ",
    Somali: "ሶማሌ",
    Tigray: "ትግራይ",
  },
  om: {
    Oromia: "Oromiyaa",
    Sidama: "Sidaamaa",
    "Central Ethiopia": "Itoophiyaa Giddu-galeessaa",
    "South Ethiopia": "Itoophiyaa Kibbaa",
    "Southwest Ethiopia": "Itoophiyaa Kibba-Lixaa",
    "Addis Ababa": "Finfinnee",
    Afar: "Afar",
    Amhara: "Amaaraa",
    "Dire Dawa": "Dirre Dhawaa",
    Gambela: "Gambeellaa",
    Harari: "Hararii",
    Somali: "Somaalee",
    Tigray: "Tigraay",
  },
};

// Flat lookup of zone display names by language. Keyed on the canonical
// English zone name used in LOCATIONS above, so this works across regions
// without needing to duplicate entries per-region.
export const ZONE_TRANSLATIONS = {
  am: {
    Arsi: "አርሲ",
    "West Arsi": "ምዕራብ አርሲ",
    Bale: "ባሌ",
    "East Bale": "ምስራቅ ባሌ",
    Borena: "ቦረና",
    Guji: "ጉጂ",
    "West Guji": "ምዕራብ ጉጂ",
    "East Hararghe": "ምስራቅ ሐረርጌ",
    "West Hararghe": "ምዕራብ ሐረርጌ",
    "East Shewa": "ምስራቅ ሸዋ",
    "West Shewa": "ምዕራብ ሸዋ",
    "North Shewa": "ሰሜን ሸዋ",
    "Southwest Shewa": "ደቡብ ምዕራብ ሸዋ",
    "East Welega": "ምስራቅ ወለጋ",
    "West Welega": "ምዕራብ ወለጋ",
    "Horo Guduru Welega": "ሆሮ ጉዱሩ ወለጋ",
    "Kellem Welega": "ቀለም ወለጋ",
    Jimma: "ጅማ",
    Illubabor: "ኢሉአባቦር",
    "Buno Bedele": "ቡኖ በደሌ",
    "Oromia Special Zone Surrounding Finfinne": "የኦሮሚያ ልዩ ዞን ዙሪያ ፊንፊኔ",
    "Hawassa City": "ሀዋሳ ከተማ",
    "Sidama Zone": "ሲዳማ ዞን",
    Gurage: "ጉራጌ",
    Silte: "ስልጤ",
    Hadiya: "ሀዲያ",
    "Kembata Tembaro": "ከምባታ ጠምባሮ",
    Halaba: "ሀላባ",
    Yem: "የም",
    Wolaita: "ወላይታ",
    Gamo: "ጋሞ",
    Gofa: "ጎፋ",
    "South Omo": "ደቡብ ኦሞ",
    Konso: "ኮንሶ",
    Derashe: "ደራሼ",
    Amaro: "አማሮ",
    Burji: "ቡርጂ",
    Keffa: "ከፋ",
    Sheka: "ሸካ",
    "Bench Sheko": "ቤንች ሸኮ",
    Dawro: "ዳውሮ",
    Konta: "ኮንታ",
    "West Omo": "ምዕራብ ኦሞ",
    Arada: "አራዳ",
    Gulele: "ጉለሌ",
    Yeka: "የካ",
    "Kolfe Keranio": "ኮልፌ ቀራንዮ",
    "Nifas Silk Lafto": "ንፋስ ስልክ ላፍቶ",
    Lideta: "ልደታ",
    "Akaki Kality": "አቃቂ ቃሊቲ",
    Bole: "ቦሌ",
    Kirkos: "ቂርቆስ",
    "Addis Ketema": "አዲስ ከተማ",
    "Lemi Kura": "ለሚ ኩራ",
    "Awusi Rasu (Zone 1)": "አውሲ ራሱ (ዞን 1)",
    "Kilbet Rasu (Zone 2)": "ቅልበት ራሱ (ዞን 2)",
    "Gabi Rasu (Zone 3)": "ገቢ ራሱ (ዞን 3)",
    "Fantena Rasu (Zone 4)": "ፋንጠና ራሱ (ዞን 4)",
    "Hari Rasu (Zone 5)": "ሀሪ ራሱ (ዞን 5)",
    "North Wollo": "ሰሜን ወሎ",
    "South Wollo": "ደቡብ ወሎ",
    "North Shewa (Amhara)": "ሰሜን ሸዋ (አማራ)",
    "East Gojjam": "ምስራቅ ጎጃም",
    "West Gojjam": "ምዕራብ ጎጃም",
    "North Gondar": "ሰሜን ጎንደር",
    "South Gondar": "ደቡብ ጎንደር",
    "Central Gondar": "መካከለኛ ጎንደር",
    "West Gondar": "ምዕራብ ጎንደር",
    Awi: "አዊ",
    "Wag Hemra": "ዋግ ኽምራ",
    "Oromia Special Zone": "የኦሮሚያ ልዩ ዞን",
    "Dire Dawa City": "ድሬ ዳዋ ከተማ",
    "Dire Dawa Rural": "ድሬ ዳዋ ገጠር",
    Anywaa: "አኝዋ",
    Nuer: "ኑዌር",
    Majang: "ማጃንግ",
    "Itang Special": "ኢታንግ ልዩ",
    "Harar City": "ሐረር ከተማ",
    "Harari Rural": "ሐረሪ ገጠር",
    "Fafan (Jijiga)": "ፋፋን (ጅግጅጋ)",
    Siti: "ሲቲ",
    Gerdhari: "ገርዳሪ",
    Liben: "ሊበን",
    Afder: "አፍደር",
    Shabelle: "ሸበሌ",
    Korahe: "ቆራሄ",
    Doolo: "ዶሎ",
    Erer: "ኤረር",
    "Mekelle City": "መቀሌ ከተማ",
    Central: "መካከለኛ",
    Eastern: "ምስራቃዊ",
    Southern: "ደቡባዊ",
    "South Eastern": "ደቡብ ምስራቃዊ",
    Northwestern: "ሰሜን ምዕራባዊ",
    Western: "ምዕራባዊ",
  },
  om: {
    Arsi: "Arsii",
    "West Arsi": "Arsii Lixaa",
    Bale: "Baalee",
    "East Bale": "Baalee Bahaa",
    Borena: "Booranaa",
    Guji: "Gujii",
    "West Guji": "Gujii Lixaa",
    "East Hararghe": "Harargee Bahaa",
    "West Hararghe": "Harargee Lixaa",
    "East Shewa": "Shawaa Bahaa",
    "West Shewa": "Shawaa Lixaa",
    "North Shewa": "Shawaa Kaabaa",
    "Southwest Shewa": "Shawaa Kibba Lixaa",
    "East Welega": "Wallagga Bahaa",
    "West Welega": "Wallagga Lixaa",
    "Horo Guduru Welega": "Horroo Guduruu Wallaggaa",
    "Kellem Welega": "Qellem Wallaggaa",
    Jimma: "Jimmaa",
    Illubabor: "Iluu Abbaa Booraa",
    "Buno Bedele": "Buunno Bedelle",
    "Oromia Special Zone Surrounding Finfinne":
      "Godina Addaa Oromiyaa Naannawa Finfinnee",
    "Hawassa City": "Magaalaa Hawaasaa",
    "Sidama Zone": "Godina Sidaamaa",
    Gurage: "Gurraagee",
    Silte: "Siltee",
    Hadiya: "Hadiyyaa",
    "Kembata Tembaro": "Kambaataa Xambaaroo",
    Halaba: "Halaabaa",
    Yem: "Yem",
    Wolaita: "Wolaayitaa",
    Gamo: "Gaamoo",
    Gofa: "Goofaa",
    "South Omo": "Omoo Kibbaa",
    Konso: "Konsoo",
    Derashe: "Derashee",
    Amaro: "Amaaroo",
    Burji: "Burjii",
    Keffa: "Kaffaa",
    Sheka: "Shakkaa",
    "Bench Sheko": "Beench Shakkoo",
    Dawro: "Daawuroo",
    Konta: "Kontaa",
    "West Omo": "Omoo Lixaa",
    Arada: "Aradaa",
    Gulele: "Gullallee",
    Yeka: "Yakkaa",
    "Kolfe Keranio": "Kolfee Qeraaniyoo",
    "Nifas Silk Lafto": "Niftaas Silkii Laaftoo",
    Lideta: "Lideettaa",
    "Akaki Kality": "Akaakii Qaallitii",
    Bole: "Boolee",
    Kirkos: "Qirqos",
    "Addis Ketema": "Adiis Katamaa",
    "Lemi Kura": "Lammii Kuraa",
    "Awusi Rasu (Zone 1)": "Awsii Raasuu (Godina 1)",
    "Kilbet Rasu (Zone 2)": "Kilbetii Raasuu (Godina 2)",
    "Gabi Rasu (Zone 3)": "Gabii Raasuu (Godina 3)",
    "Fantena Rasu (Zone 4)": "Faantena Raasuu (Godina 4)",
    "Hari Rasu (Zone 5)": "Harii Raasuu (Godina 5)",
    "North Wollo": "Walloo Kaabaa",
    "South Wollo": "Walloo Kibbaa",
    "North Shewa (Amhara)": "Shawaa Kaabaa (Amaaraa)",
    "East Gojjam": "Gojjaam Bahaa",
    "West Gojjam": "Gojjaam Lixaa",
    "North Gondar": "Gondar Kaabaa",
    "South Gondar": "Gondar Kibbaa",
    "Central Gondar": "Gondar Giddu-galeessaa",
    "West Gondar": "Gondar Lixaa",
    Awi: "Awwii",
    "Wag Hemra": "Waag Hemraa",
    "Oromia Special Zone": "Godina Addaa Oromiyaa",
    "Dire Dawa City": "Magaalaa Dirre Dhawaa",
    "Dire Dawa Rural": "Baadiyyaa Dirre Dhawaa",
    Anywaa: "Anywaa",
    Nuer: "Nuer",
    Majang: "Majangir",
    "Itang Special": "Itang Addaa",
    "Harar City": "Magaalaa Harar",
    "Harari Rural": "Baadiyyaa Hararii",
    "Fafan (Jijiga)": "Faafan (Jijiga)",
    Siti: "Sitti",
    Gerdhari: "Gerdhari",
    Liben: "Liiban",
    Afder: "Afdheer",
    Shabelle: "Shabeelle",
    Korahe: "Qoraahe",
    Doolo: "Doolo",
    Erer: "Ererr",
    "Mekelle City": "Magaalaa Mekelle",
    Central: "Giddu-galeessaa",
    Eastern: "Bahaa",
    Southern: "Kibbaa",
    "South Eastern": "Kibba-Bahaa",
    Northwestern: "Kaaba-Lixaa",
    Western: "Lixaa",
  },
};


export const getLocalizedRegions = (lang = "en") => {
  const labels = REGIONS_LOCALIZED[lang] || REGIONS_LOCALIZED.en;
  return REGIONS.map((region) => ({
    value: region,
    label: labels[region] || region,
  }));
};


export const getLocalizedZones = (region, lang = "en") => {
  const zones = getZonesByRegion(region);
  if (lang === "en") return zones.map((z) => ({ value: z, label: z }));
  const dict = ZONE_TRANSLATIONS[lang] || {};
  return zones.map((z) => ({ value: z, label: dict[z] || z }));
};


export const WEREDA_TRANSLATIONS = {
  am: {},
  om: {},
};

export const getLocalizedWereda = (region, zone, lang = "en") => {
  const weredas = getWeredaByZone(region, zone);
  if (lang === "en") return weredas.map((w) => ({ value: w, label: w }));
  const dict = WEREDA_TRANSLATIONS[lang] || {};
  return weredas.map((w) => ({ value: w, label: dict[w] || w }));
};
